### ISSUE TITLE
MariaDB Version Parsing

### ISSUE THREAD

**Issue by khill-fbmc** [minthcm/minthcm#58]
Hello,

I am trying to install this software and ran into the issue where it said my MariaDB version was not supported.

[I dug into the sources to see why, and it appears that it should work](https://github.com/minthcm/minthcm/blob/ceb04d587632d6bf28e4a19d09c0a85ed45e285d/MintHCM/include/database/MysqlManager.php#L1520). If I am not mistaken, shouldn't `10.6.4` pass the check for `10.2`? or is that a strict version.

I also wondered if the version string is not just numbers since I can see `maria~focal` tacked on there. Is it possible that the extra bit there is messing up the version comparison?

**Comment by MintHCM-admin** [comment]
Hi,

The error is on our side. We didn't specify that MintHCM only supports MariaDB versions 10.0-10.3. We apologize and we are in the process of updating the information on our websites.

Your issue occurs because the system does not support your version of MariaDB. The system requirements are: PHP 7.1 and MySQL 5.5-5.7 or MariaDB 10.0-10.3.

Best regards!
MintHCM Team
