### ISSUE TITLE
After installtion Minthch 4.0.2, stack on the login page 

### ISSUE THREAD

**Issue by habiboedris** [minthcm/minthcm#62]
Dear Mint HCM community 

I have installed the MintHCM on my local computer using Xampp Web Server after the installation was completed, I tried to log in to the system, and after providing the login details loops  to the login page 
![mint HCM login page error](https://github.com/minthcm/minthcm/assets/17234049/7587164b-1600-4c21-9273-47418a894e3a)

Best
Habib.E

**Comment by MintHCM-admin** [comment]
Hi, we are delighted you want to share your code with us.

Do you have any examples of use cases for the code?

However, we will not add the code to our projects because we recommend integrating this kind of solution into configuration files. By adding the configuration to the api\constants files, you will not need to rebuild the frontend application as the configuration will be downloaded from the backend.

**Comment by MintHCM-admin** [comment]
Hello,

Could you please share the following logs with us: php.log, minthcm.log, and install.log? Additionally, we need to know which PHP version and database you are using.

If you prefer, you could wait until the next version is released. It will be available this week.

**Comment by MintHCM-admin** [comment]
Hello! 
The new version is available. Have you tried it? 
Let us know
