### ISSUE TITLE
SAML and LDAP removed from frontend?

### ISSUE THREAD

**Issue by VincentSC** [minthcm/minthcm#66]
Trying MintHCM again. :)

In https://github.com/minthcm/minthcm/issues/56#issuecomment-1876071865 I already remarked that SAML does not work anymore. Given the remark in https://github.com/minthcm/minthcm/issues/57#issuecomment-1537939423 `Usually, we have problems with SAML. It means, it works after a few corrections in code :)`, I assumed it would work in a few months, so I just waited.

But now I found neither LDAP works. Could the "a few corrections in code" be done to get it working again? Pretty please? :)

**Comment by MintHCM-admin** [comment]
Hello!
We are currently working on MintHCM, and some functionalities that worked in version 3 may not work properly in version 4. This could be due to the significant architectural changes made in the system. 

Unfortunately, we are currently unable to verify all configuration possibilities. We encourage you to review the situation and propose any necessary changes.

Additionally, in our organization, we are successfully using the latest version of MintHCM in a production environment, including LDAP, without encountering any issues.
