### ISSUE TITLE
Love the product UI

### ISSUE THREAD

**Issue by sanjayws** [minthcm/minthcm#70]
Just wanted to thank the devs for this great software.

My only "concern" is, that we have to use Elasticsearch which really requires so much resources, makes using Minthcm undesirable for small setups like mine .... perhaps the installs could have option to uncheck use of Elasticsearch and likely will break the search function, which is fine (for now).

**Comment by MintHCM-admin** [comment]
Hello sanjayws,
Thank you for your feedback and kind words 😊. We truly appreciate it.

When designing our system, we made Elasticsearch a mandatory component to enhance the application's performance. We didn't anticipate scenarios where it might not be feasible to include it. However, your perspective on this issue is reasonable and valuable.

While we can't promise to allow installations without Elasticsearch at this moment, we will certainly consider whether and when we might want to add such an option in the future.

Thank you again for your insights.

Best regards,  
Martin from MintHCM

**Comment by sanjayws** [comment]
Thanks for taking the time to reply ...again, just love the UI, love the product, kudos and wish you and Minthcm all the best

**Comment by MintHCM-admin** [comment]
Thank you so much for your kind words and support @sanjayws! We're thrilled to hear that you love the UI and the product. Your feedback is invaluable to us, and we truly appreciate your understanding regarding the Elasticsearch requirement. We'll keep your suggestion in mind as we continue to improve MintHCM.

Best wishes,
Martin
